version: '3.7'

services:
  node:
    container_name: ${APP_NAME}
    build:
      context: .
      dockerfile: docker/docker-chatapp.dockerfile
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
        - '${APP_PORT}:${APP_PORT}'
        - '9229:9229'
    networks:
        - ${APP_NAME}-network
  
  # mongodb:
  #   image: 'mongo:latest'
  #   container_name: 'mongodb'
  #   restart: always
  #   environment: 
  #     - MONGO_INITDB_DATABASE=${MONGO_DATABASENAME}
  #     - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
  #     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
  #   volumes:
  #     - mongodata:/data/db
  #     - ./src/services/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  #   ports: 
  #     - ${MONGO_PORT}:${MONGO_PORT}
  #   # command: ["--replSet", "rs0", "--bind_ip_all"]
  #   networks:
  #     - ${APP_NAME}-network

  cache:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - '${REDIS_PORT_DOCKER}:${REDIS_PORT_DOCKER}'
    command: /bin/sh -c "redis-server /etc/redis.conf"
    volumes:
      - redisdata:/data
      - ./docker/config/redis.conf:/etc/redis.conf
    networks:
      - ${APP_NAME}-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - '${ELASTICSEARCH_PORT}:${ELASTICSEARCH_PORT}'
    networks:
      - ${APP_NAME}-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.0
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:${ELASTICSEARCH_PORT}"
    ports:
      - '${KIBANA_PORT}:${KIBANA_PORT}'
    depends_on:
      - 'elasticsearch'
    networks:
        - ${APP_NAME}-network

volumes:
    esdata:
      driver: local
    mongodata:
      driver: local
    redisdata:
      driver: local

networks:
    chatapp-network:
      driver: bridge
