const ONE_HOUR = 1000 * 60 * 60

const TWELVE_HOURS = ONE_HOUR * 12

module.exports = {
    BCRYPT_MAX_BYTES,
    BCRYPT_MAX_BYTES,
    EMAIL_VERIFICATION_TIMEOUT = TWELVE_HOURS,
    EMAIL_VERIFICATION_TOKEN_BYTES,
    SIGNATURE_BYTES,
    PASSWORD_RESET_BYTES,
    PASSWORD_RESET_TIMEOUT = ONE_HOUR
  } = process.env;
