const {
  APP_HOSTNAME,
  APP_HOSTNAME_DOCKER,
  ELASTICSEARCH_USERNAME,
  ELASTICSEARCH_PASSWORD,
  ELASTICSEARCH_PORT,
  KIBANA_PORT
} = process.env;

module.exports.ELASTICSEARCH_OPTIONS = {
  hostname: APP_HOSTNAME,
  port: ELASTICSEARCH_PORT,
  username: ELASTICSEARCH_USERNAME,
  password: ELASTICSEARCH_PASSWORD
};
